## Number 1 is Command line Variables
## Number 2 is Task Level Variables
## Number 3 is Variables from files
## Number 4 Play level Variables
## Number 5 is Inventory Variables

- name: Variable on Play level
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
 # Note: if we declare a variable in PLAY level then all the tasks can access that variable.

- name: variables from file in Play Level
  hosts: all
  vars_files:
   - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
 # We can load all the variables from a file, since it is on play level, all the tasks can access those variables

- name: Variables on Task Level
  hosts: all
  tasks:
    - name: print URL in Task1
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: task1.example.com
        
    - name: print URL in Task2
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: task2.example.com
# Scope of task variable is only to that task, the other task cannot access the other tasks variablesS

- name: Variable from inventory
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL == {{URL}}
        
        
## Variable Precedence
- name: Variable Precedence
  hosts: all
  vars:
    URL: play.example.com
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: task.example.com
        
## Print Hostname of remote note
- name: Print Hostname of remote node
  hosts: all
  tasks:
    - name: print Hostname
      ansible.builtin.debug:
        msg: Hostname = {{ansible_hostname}}
    - name: Print processor info
      ansible.builtin.debug:
        msg: "{{ansible_processor}}"
