- name: Variable on Play level
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
 # Note: if we declare a variable in PLAY level then all the tasks can access that variable.

- name: variables from file in Play Level
  hosts: all
  vars_files:
   - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
 # We can load all the variables from a file, since it is on play level, all the tasks can access those variables

- name: Variables on Task Level
  hosts: all
  tasks:
    - name: print URL in Task1
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: task1.example.com
        
    - name: print URL in Task2
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: task2.example.com
  